# This workflow builds and pushes an Azure Artifact when a commit
# is pushed to a branch matching "deploy" or triggered manually via workflow_dispatch.
#
# Prerequisites:
# 1. You have set the AZURE_ARTIFACTS_PAT secret.

name: Build & Publish Contracts

on:
  push:
    branches:
      - deploy

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Configure NuGet for Azure Artifacts
        run: |
          dotnet nuget add source "https://pkgs.dev.azure.com/alpinelis/AlpineFrameworks/_packaging/AlpineFrameworks/nuget/v3/index.json" \
            --name "AlpineFrameworks" \
            --username "github-actions" \
            --password "${{ secrets.AZURE_ARTIFACTS_PAT }}" \
            --store-password-in-clear-text

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Push to Azure Artifacts
        run: dotnet nuget push ./artifacts/*.nupkg --api-key "AzureArtifacts" --source "AlpineFrameworks" --skip-duplicate